# Generated by Django 4.2.6 on 2024-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='events',
            field=models.ManyToManyField(related_name='user_groups', to='event_management.event'),
        ),
    ]
